<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('assets')->insert(
            [
                [
                    "piping_id" => "Pipe 101A",
                    "piping_name" => "Piping Number 101A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-10",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ],
                [
                    "piping_id" => "Pipe 102A",
                    "piping_name" => "Piping Number 102A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-11",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ],
                [
                    "piping_id" => "Pipe 103A",
                    "piping_name" => "Piping Number 103A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-12",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ],
                [
                    "piping_id" => "Pipe 104A",
                    "piping_name" => "Piping Number 104A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-13",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ],
                [
                    "piping_id" => "Pipe 105A",
                    "piping_name" => "Piping Number 105A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-14",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ],
                [
                    "piping_id" => "Pipe 106A",
                    "piping_name" => "Piping Number 106A",
                    "nominal_pipe_size" => 0.1,
                    "pipe_design_code" => 0.15,
                    "schedule" => 0.2,
                    "outside_diameter" => 0.25,
                    "longtd_quality_factor" => 0.3,
                    "weld_joint_factor" => 0.35,
                    "allowable_unit_stress" => 0.4,
                    "coefficient" => 0.45,
                    "min_design_pressure" => 0.5,
                    "max_design_pressure" => 0.55,
                    "min_design_temperature" => 0.6,
                    "max_design_temperature" => 0.7,
                    "corrosion_allowance" => 0.7,
                    "mechanical_allowance" => 0.7,
                    "min_structural_thickness" => 0.7,
                    "min_alert_thickness" => 0.7,
                    "nominal_thickness" => 0.7,
                    "class" => 1,
                    "date_in_service" => "2023-06-15",
                    "notes" => "",
                    "attachment" => "",
                    "images" => "",
                    "recomendation" => "add inspection data",
                    "qr_code" => "www.google.com"
                ]
            ]
        );
    }
}
